# Generated by Django 3.1.2 on 2020-12-22 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='time_complet',
        ),
    ]
