# Generated by Django 3.1.6 on 2021-06-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20210606_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en_us',
            field=models.CharField(help_text='category name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(help_text='category name', max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='name_en_us',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='mymodel',
            name='name_ru',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
